title = 'q3st1on'
theme = 'rusty-typewriter'
enableEmoji = true
locale = "en-US"
enableRobotsTXT = true

# rtwt = Rusty Typewriter Theme
[params.rtwt.side.home]
taxonomies = ['tags','types','series']
countTaxonomy = 3
sidePaneSticky = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
tag = 'tags'
type = 'types'
topic = 'topics'
series = 'series'

[params.author]
name = 'q3st1on'

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 1

[[menus.main]]
name = 'Archive'
pageRef = '/archive'
weight = 2

# build search index ================
[outputFormats]
 [outputFormats.SearchIndex]
  mediaType = "application/json"
  baseName = "searchindex"
  isPlainText = true
  notAlternative = true

[mediaTypes]
 [mediaTypes."application/json"]
  suffixes = ["json"]

[outputs]
 home = ["HTML","RSS","SearchIndex"]
# ===================================

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.footnote]
enable = true
enableAutoIDPrefix = true
backlinkHTML = "↑"

[markup.goldmark.extensions.passthrough.delimiters]
block = [['$$', '$$'], ['\[', '\]']]
inline = [['$', '$'], ['\(', '\)']]

[markup.highlight]
codeFences = true
noClasses = false